name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.04.9+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0e534b9537e835a2f48e54581304bd0d430f1db91066c39775a1e295b40ce85"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"
