name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.04.9+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebe7c0a62f2758e0dbf27e05b2262d1e76a5306853b3bd8c9fdb7a297ba0dec2"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
