name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.04.9+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a07fcdcf22fdb9f538ea17452228691aa86aa30f5fd5ae3325bc6ba3dce0485"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
