name = "2000s-edition"
author = "NicSonic"
version = "v1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d9c0ede60886883abcaf086522705a189cce5337de8b7e93a4aa94127816273"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
