name = "2000s-edition"
author = "NicSonic"
version = "v1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a7ed7556184cb9b25af1679cd18855010a91be13f3d1117bea2fc7c478d9198"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
