name = "2000s-edition"
author = "NicSonic"
version = "v1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3140089217b6f3de724208cb55bf60f6ec15d03676a5d317eea23785d2d9771"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
