name = "2000s-edition"
author = "NicSonic"
version = "v1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb4ca6cf281d03db96b675d8d00e19c6e991a2ec31ff9222f171a9d4b721405d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
