name = "Re-Console Plus"
author = "omo50"
version = "26.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a27bd1a13201902efbe0a3e5ceed7d9f020cfd117e5e45116861a72884ac5226"

[versions]
fabric = "0.19.1"
minecraft = "26.1.1"
