name = "Re-Console Plus"
author = "omo50"
version = "26.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "004ac91baa4851b8530dc90bbce2f1f7d7673d071ee42d9d9716e592cd6eed7e"

[versions]
fabric = "0.19.1"
minecraft = "26.1.1"
