name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.04.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7d1b09d89c124ba5a69f33d9288a94c2286c81f8b55b6a9dfb2233c205201e1"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
