name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.04.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21d83d2d419e0cb2e430e7f37cda7f690666b0260d9d9d2354fb0489fc65fd2d"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
