name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.04.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "883cadb0a0642f099b87a487ee018f33352864a41b562acc0868ee01e201d882"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
