name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a774aae181792db9c0331de48bfc41677f3035c2193398fbec785df6a36002df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
