name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-gdc-2012"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6552ff764ab76af18cb522e092932aaf5e8cf093b7cf7a161bc73872f17158c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
