name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-gdc-2012"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba498e7dd26ac701e3d0dc79e4f3826f2a340a7d1ba2a8956658ab8bc8a95b19"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
