name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-gdc-2012"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "948b9ccd8286d02d996fde92244e4cee787aef5040855e31afdc6c26bce44524"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
