name = "Re-Console+"
author = "omo50, Cjnator38"
version = "26.05.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edd91b7ca131b8306b5e42d48daefdc3abb95134003254bcbb6237b01f9b5941"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
