name = "Re-Console+"
author = "omo50, Cjnator38"
version = "26.06.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b50fafb9464d099e52a1fcb510fe48ee6fd6f8f32e919fa5d6f9cc59fdae9325"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
