name = "Re-Console+"
author = "omo50, Cjnator38"
version = "26.05.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12148d7599e60faa6b3e400d6313548c8eebb9107f1a83b1da441a8b0fbd6b37"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
