name = "2000s-edition"
author = "NicSonic"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2f902cb78f0e2a60af5c9b2a5cc0d5cbda9f4c33b23c5be77f3117509a117f3"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./resources/datapack/required/"
