name = "2000s-edition"
author = "NicSonic"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9a126794d1d9fef198c6a0a49d836ff2296c9010e922a4cc51da88ff69090a8"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./resources/datapack/required/"
