name = "2000s-edition"
author = "NicSonic"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c2a307f3cff0f9fcd993f9e7f049e17c37a459267ea6abe3ff04506a6926c84"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./resources/datapack/required/"
