[workspace]
resolver = "2"
members = [
    "crates/packwand-instance",
    "crates/packwand-launch",
    "crates/packwand-runtime",
    "crates/packwand-minecraft",
    "crates/packwand-auth",
    "crates/packwand-devboot",
    "crates/packwand-msa",
    "crates/packwand-core-probe",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://git.nostalgica.net/Lasting-Legacy/Lasting-Legacy-Monorepo"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
tempfile = "3"
packwand-instance = { path = "crates/packwand-instance" }
packwand-launch = { path = "crates/packwand-launch" }
packwand-runtime = { path = "crates/packwand-runtime" }
packwand-minecraft = { path = "crates/packwand-minecraft" }
packwand-auth = { path = "crates/packwand-auth" }
packwand-devboot = { path = "crates/packwand-devboot" }
packwand-msa = { path = "crates/packwand-msa" }
sha1 = "0.10"
md-5 = "0.10"
regex-lite = "0.1"
ureq = { version = "2", features = ["gzip"] }
zip = { version = "6", default-features = false, features = ["deflate"] }
