name = "Vital"
author = "omo50, intergrav, blryface"
version = "26.05.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "126422b98bbec493edc8e146a916b0cbc4fdeccba4cd73567a48e562a68d11e2"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
