name = "Vital"
author = "omo50, intergrav, blryface"
version = "26.05.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48c2c0f9bedae272ae7e70693713397aad9d66d68568544ca6bba2b9d81ae5f5"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
