{
  # Nix consumption of the monorepo's modpacks via the vendored packwiz2nix
  # (lib/packwiz2nix). The checksums.json files consumed here are generated by
  # packwand itself — `task gen-nix` or `packwand nix gen [--all]` — using
  # packwand's own manifest parsing and verified download cache.
  description = "Lasting Legacy monorepo pack tooling (packwiz2nix integration)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    packwiz2nix = {
      url = "path:./lib/packwiz2nix";
      flake = true;
    };
  };

  outputs = { self, nixpkgs, packwiz2nix }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

      # Every modpack subdir (modpacks/<pack>/<key>-{mr,cf}) with a generated
      # checksums.json.
      packsWithChecksums =
        let
          inherit (builtins) readDir attrNames filter pathExists concatMap;
          packs = filter (name: (readDir ./modpacks).${name} == "directory")
            (attrNames (readDir ./modpacks));
          subdirsOf = pack:
            let contents = readDir (./modpacks + "/${pack}");
            in filter
              (sub: contents.${sub} == "directory"
                && pathExists (./modpacks + "/${pack}/${sub}/checksums.json"))
              (attrNames contents);
        in
        concatMap (pack: map (sub: { inherit pack sub; }) (subdirsOf pack)) packs;
    in
    {
      # Re-export the packwiz2nix helpers (mkPackwizPackages, mkModLinks,
      # mkMultiMCPack, ...) for downstream flakes.
      lib = packwiz2nix.lib;

      # legacyPackages.<system>."<pack>/<subdir>" = attrset of mod derivations,
      # ready for packwiz2nix.lib.mkModLinks / nix-minecraft symlinks.
      legacyPackages = forAllSystems (pkgs:
        builtins.listToAttrs (map
          (e: {
            name = "${e.pack}/${e.sub}";
            value = packwiz2nix.lib.mkPackwizPackages pkgs
              (./modpacks + "/${e.pack}/${e.sub}/checksums.json");
          })
          packsWithChecksums));
    };
}
