pack_directory = "resourcepacks/external/lce-resources"
output_file_path = "output.zip"
recompress_compressed_files = true
zip_compression_iterations = 5
automatic_minecraft_quirks_detection = true

["**/*.{json,mcmeta}"]
minify_json = true

["**/*.{flac,wav}"]
ogg_obfuscation = true
channels = 2
sampling_frequency = 44100
target_pitch = 1.5

["**/*.png"]
image_data_compression_iterations = 15
png_obfuscation = true

[[filters]]
path = "**/1_20_2/**"
action = "copy"
[[filters]]
path = "**/1_21_2/**"
action = "copy"
[[filters]]
path = "**/1_21_6/**"
action = "copy"
[[filters]]
path = "**/1_21_9/**"
action = "copy"
[[filters]]
path = "**/background.png"
action = "copy"