#!/bin/bash
echo Updating
(cd ./modpacks/simply-legacy/mr/yarn/1.21.10-fabric && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/simply-legacy/cf/yarn/1.21.10-fabric && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/re-console+/mr/yarn/1.21.10-fabric && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/re-console+/cf/yarn/1.21.10-fabric && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/rekindled-legacy/mr/forged/b0033 && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/rekindled-legacy/mr/forged/b0035 && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/rekindled-legacy/mr/forged/b0054 && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/rekindled-legacy/mr/forged/gdc2012 && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/rekindled-legacy/mr/forged/tu0 && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/rekindled-legacy/mr/forged/tu1 && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/rekindled-legacy/mr/forged/tu2 && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/rekindled-legacy/mr/forged/tu3 && packwiz refresh -y && packwiz update -a -y)
(cd ./modpacks/rekindled-legacy/mr/forged/tu5 && packwiz refresh -y && packwiz update -a -y)