name = "Simply Optimized Forked"
author = "hsza, omo50"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "addf7720b014e2d6ae52241201279ed3dadb286dbb71192aaedbd6fddc03e8d9"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
