name = "Simply Optimized Forked"
author = "hsza, omo50"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1cc1b68c1a913ac6ebc08e170ee035ec8fd41e086801b4b10fe996b3a9db240"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
