name = "Simply Archaic"
author = "omo50"
version = "26.05-mc1.8.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb4c242efc5276bd04af3755fc81fc83533953fd54f7696d10a45bdb7b2cb037"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
