name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-gdc-2012"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ae5f850311a79b7be6793a01075830d462c385fcc4bfb89634be954cfa1d601"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
