name: "Auto Update & Refresh"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-update:
    uses: ./.forgejo/workflows/packwand-task.yml
    with:
      verb: workspace update
      commit-message: 'actions: auto-update'
    secrets:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
