name: "Auto Update & Refresh"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-update:
    runs-on: technocality
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}
          fetch-depth: 1
          filter: blob:none
          sparse-checkout: |
            modpacks
            src/actions/somnus

      - name: Cache Somnus Binary
        id: cache-somnus
        uses: actions/cache@v4
        with:
          path: ./somnus-bin
          key: somnus-go-v1-${{ runner.os }}-${{ hashFiles('src/actions/somnus/**/*.go', 'src/actions/somnus/go.mod') }}

      - name: Setup Go
        if: steps.cache-somnus.outputs.cache-hit != 'true'
        uses: https://github.com/actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Build Somnus
        if: steps.cache-somnus.outputs.cache-hit != 'true'
        run: |
          go build -C src/actions/somnus -o "$GITHUB_WORKSPACE/somnus-bin/somnus" .
          chmod +x ./somnus-bin/somnus

      - name: Cache Packwiz Binary
        id: cache-packwiz
        uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: go-bin-packwiz-v1-${{ runner.os }}

      - name: Setup Go Dos
        if: steps.cache-packwiz.outputs.cache-hit != 'true' && steps.cache-somnus.outputs.cache-hit == 'true'
        uses: https://github.com/actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Install Packwiz
        if: steps.cache-packwiz.outputs.cache-hit != 'true'
        run: go install github.com/packwiz/packwiz@latest

      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run Update
        run: ./somnus-bin/somnus update

      - name: Commit
        uses: https://github.com/EndBug/add-and-commit@v9
        with:
          author_name: forgejo-actions[bot]
          author_email: omo50@noreply.nostalgica.net
          message: 'actions: auto-update (${{ github.workflow }})'
          add: 'modpacks'

