name: "Auto Update & Refresh"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  auto-update:
    runs-on: technocality
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with: 
          token: ${{ secrets.FORGEJO_TOKEN }}
          fetch-depth: 1
          sparse-checkout: |
            modpacks
            src/actions

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Cache Packwiz Binaries
        id: cache-tooling
        uses: actions/cache@v4
        with:
          path: $HOME/go/bin
          key: tooling-${{ runner.os }}-packwiz

      - name: Install Tooling
        if: steps.cache-tooling.outputs.cache-hit != 'true'
        run: |
          mkdir -p $HOME/go/bin
          go install github.com/packwiz/packwiz@latest
          go install github.com/Merith-TK/packwiz-wrapper/cmd/pw@main
      
      - name: Add Path
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Cache Updater
        id: cache-updater
        uses: actions/cache@v4
        with:
          path: ./updater-bin
          key: updater-v3-${{ runner.os }}-${{ hashFiles('src/actions/updater/**') }}

      - name: Rust Cache
        if: steps.cache-updater.outputs.cache-hit != 'true'
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src/actions/updater -> target"

      - name: Build Updater
        if: steps.cache-updater.outputs.cache-hit != 'true'
        run: |
          cargo build --release --manifest-path src/actions/updater/Cargo.toml
          mkdir -p ./updater-bin
          cp src/actions/updater/target/release/updater ./updater-bin/updater

      - name: Run Updater
        id: rust-update
        continue-on-error: true
        run: |
          chmod +x ./updater-bin/updater
          ./updater-bin/updater

      - name: Run Shell Updater
        if: steps.rust-update.outcome == 'failure'
        run: |
          echo "Rust Updater failed. Falling back to Shell..."
          chmod +x ./modpacks/update-refresh.sh
          ./modpacks/update-refresh.sh

      - name: Commit
        uses: https://github.com/EndBug/add-and-commit@v9
        with:
          author_name: forgejo-actions[bot]
          author_email: omo50@noreply.nostalgica.net
          message: 'actions: auto-update (${{ github.workflow }})'
          add: 'modpacks'