name: "Bulk Refresh"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bulk-refresh:
    uses: ./.forgejo/workflows/packwand-task.yml
    with:
      verb: workspace refresh
      commit-message: 'actions: bulk refresh'
