name: "Bulk Update"

on:
  workflow_dispatch:

jobs:
  bulk-update:
    runs-on: technocality
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}
          fetch-depth: 1
          filter: blob:none
          sparse-checkout: |
            modpacks
            tools/auto-update

      - name: Cache Packwiz Binary
        id: cache-go
        uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: go-bin-packwiz-v1-${{ runner.os }}

      - name: Setup Go
        if: steps.cache-go.outputs.cache-hit != 'true'
        uses: https://github.com/actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Install Packwiz
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: go install github.com/packwiz/packwiz@latest

      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run Bulk Update
        run: |
          chmod +x tools/auto-update/update.sh
          tools/auto-update/update.sh

      - name: Commit
        uses: https://github.com/EndBug/add-and-commit@v9
        with:
          author_name: forgejo-actions[bot]
          author_email: omo50@noreply.nostalgica.net
          message: 'actions: bulk update all'
          add: 'modpacks'
