name: "Bulk Update"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bulk-update:
    uses: ./.forgejo/workflows/somnus-task.yml
    with:
      verb: update
      commit-message: 'actions: bulk update all'