name: 'CI - Packwand Social'

on:
  push:
    branches: ['main']
    paths:
      - 'apps/packwandrs/packwand-social/**'
      - '.forgejo/actions/setup-go/**'
      - '.forgejo/actions/setup-just/**'
      - '.forgejo/workflows/ci-packwand-social.yml'
      - 'justfile'
  pull_request:
    branches: ['main']
    paths:
      - 'apps/packwandrs/packwand-social/**'
      - '.forgejo/actions/setup-go/**'
      - '.forgejo/actions/setup-just/**'
      - '.forgejo/workflows/ci-packwand-social.yml'
      - 'justfile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  social:
    runs-on: technocality
    timeout-minutes: 20
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v5
        with:
          filter: blob:none
          fetch-depth: 1
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /apps/packwandrs/packwand-social/
            /justfile
            /.forgejo/actions/
      - uses: ./.forgejo/actions/setup-go
      - uses: ./.forgejo/actions/setup-just
      - name: Lint Packwand social
        run: just lint-social
      - name: Test Packwand social
        run: just test-social
      - name: Build Packwand social
        run: just build-social
