name: "CI - Packeater"

on:
  push:
    branches: ["main"]
    paths:
      - "apps/packwandrs/packeater/**"
      - ".forgejo/actions/setup-packeater/**"
      - ".forgejo/workflows/ci-packeater.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "apps/packwandrs/packeater/**"
      - ".forgejo/actions/setup-packeater/**"
      - ".forgejo/workflows/ci-packeater.yml"
  workflow_dispatch:

jobs:
  packeater:
    runs-on: docker
    container:
      image: rustlang/rust:nightly
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v5
      - name: Format
        working-directory: apps/packwandrs/packeater
        run: cargo fmt --package packeater_cli -- --check
      - name: Lint
        working-directory: apps/packwandrs/packeater
        run: cargo clippy -p packeater_cli --all-targets -- -D warnings
      - name: Test
        working-directory: apps/packwandrs/packeater
        run: cargo test -p packeater_cli
      - name: Build
        working-directory: apps/packwandrs/packeater
        run: cargo build --release -p packeater_cli
