name: "Validate Datapacks"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'datapacks/**'
      - '.actions/data/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: technocality
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            datapacks
            .actions/data
            .actions/resources
            .actions/publish
            .actions/builder
            .actions/linter
            .actions/updater

      - name: Install Rust
        run: |
          if ! command -v cargo &> /dev/null; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi

      - name: Run Validator
        run: |
          [ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
          cargo run --release --manifest-path .actions/data/Cargo.toml