name: "Linter"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'modpacks/**/*.json'
      - 'modpacks/**/*.toml'
      - 'resourcepacks/**/*.json'
      - 'datapacks/**/*.json'
  pull_request:

jobs:
  lint:
    runs-on: technocality
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          sparse-checkout: |
            modpacks
            resourcepacks
            datapacks
            src/actions/somnus

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src/actions/somnus/core -> target"

      - name: Cache Linter Binaries
        id: cache-linter
        uses: actions/cache@v4
        with:
          path: ./linter-bin
          key: linter-${{ runner.os }}-${{ hashFiles('src/actions/somnus/core/**/*.rs') }}

      - name: Build Linters
        if: steps.cache-linter.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./linter-bin
          cargo build --release --manifest-path src/actions/somnus/core/Cargo.toml
          cp src/actions/somnus/core/target/release/json-linter ./linter-bin/
          cp src/actions/somnus/core/target/release/toml-linter ./linter-bin/

      - name: Run Linters
        run: |
          echo "Running JSON Linter..."
          ./linter-bin/json-linter
          
          echo "Running TOML Linter..."
          ./linter-bin/toml-linter