name: 'Loader Update'

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'loader target'
        type: choice
        options:
          - latest
          - recommended
        default: latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  loader-update:
    uses: ./.forgejo/workflows/packwand-task.yml
    with:
      verb: batch loader-update ${{ inputs.target }}
      commit-message: 'actions: bulk loader update (${{ inputs.target }})'
