name: "Packwand CI"

on:
  push:
    branches: ["main"]
    paths:
      - 'src/packwand/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'src/packwand/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: technocality
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v5
        with:
          fetch-depth: 1
          filter: blob:none
          sparse-checkout: src/packwand

      - uses: https://github.com/actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Build
        run: go build ./...
        working-directory: src/packwand

      - name: Vet
        run: go vet ./...
        working-directory: src/packwand

      - name: Test
        run: go test ./...
        working-directory: src/packwand
