name: "png tyhingh"

on:
  workflow_dispatch:

jobs:
  bulk-nuke:
    runs-on: technocality
    steps:
      - name: grab
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: blob:none

      - name: install
        run: |
          if ! command -v cargo &> /dev/null; then
            echo "Rust not found. Bootstrapping..."
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          fi
          
          . "$HOME/.cargo/env"
          
          if ! command -v oxipng &> /dev/null; then
            echo "Installing oxipng..."
            cargo install oxipng
          fi
          
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: comp
        run: |
          . "$HOME/.cargo/env"
          
          oxipng -r -o 4 -v --strip all "resourcepacks/"

      - name: commit
        uses: https://github.com/EndBug/add-and-commit@v9
        with:
          author_name: forgejo-actions[bot]
          author_email: omo50@noreply.nostalgica.net
          message: 'chore: bulk'
          add: 'resourcepacks/**/*.png'