name: "Publish"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'modpacks/**/manifest.json'
      - 'datapacks/**/manifest.json'
      - 'resourcepacks/**/manifest.json'

jobs:
  publish:
    runs-on: technocality
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 
          filter: blob:none

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Changelog
        id: changelog
        run: |
          # The blobless fetch allows this git command to work perfectly
          MANIFEST=$(git diff-tree --no-commit-id --name-only -r HEAD | grep 'manifest.json' | head -n 1)
          echo "manifest=$MANIFEST" >> $GITHUB_OUTPUT
          
          npx tsx src/scripts/changelog.ts "$MANIFEST"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Cache Packwiz Binaries
        id: cache-go
        uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: go-bin-v1-${{ runner.os }}

      - name: Install packwiz
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: go install github.com/packwiz/packwiz@latest

      - name: Add Path
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src/actions -> target"

      - name: Run Publisher
        id: meta
        run: |
          cargo run --release --manifest-path src/actions/Cargo.toml --bin publish -- "${{ steps.changelog.outputs.manifest }}"

      - name: Upload to Platforms
        if: "steps.meta.outputs.mr_id != ''"
        uses: https://github.com/Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ steps.meta.outputs.mr_id }}
          modrinth-token: ${{ secrets.MR }}
          modrinth-files: "${{ github.workspace }}/${{ steps.meta.outputs.path }}/artifacts/*.mrpack"
          curseforge-id: ${{ steps.meta.outputs.cf_id }}
          curseforge-token: ${{ secrets.CF }}
          curseforge-files: "${{ github.workspace }}/${{ steps.meta.outputs.path }}/artifacts/*.zip"
          name: "${{ steps.meta.outputs.name }}"
          version: "${{ steps.meta.outputs.ver }}"
          changelog: "${{ steps.changelog.outputs.notes }}"
          loaders: ${{ steps.meta.outputs.type == 'modpack' && 'fabric' || 'minecraft' }}
          game-versions: "${{ steps.meta.outputs.mc }}"