name: Build Resource Pack
on:
  push:
    branches: [ "main" ]
    paths:
      - 'resourcepacks/**'
      - '!resourcepacks/external/lce-resources/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: technocality
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build
        id: build
        run: |
          pack=$(git diff --name-only HEAD~1 HEAD | grep '^resourcepacks/' | sed 's|resourcepacks/[^/]*/\([^/]*\)/.*|\1|' | sort -u | head -1)
          dir=$(find ./resourcepacks -type d -name "$pack" | head -1)
          echo "pack=$pack" >> $GITHUB_OUTPUT
          curl -L \
            $(curl -s https://api.github.com/repos/ComunidadAylas/PackSquash/releases/latest \
            | grep "browser_download_url" \
            | grep "x86_64-unknown-linux-musl" \
            | cut -d '"' -f 4) \
            -o /tmp/packsquash
          chmod +x /tmp/packsquash
          cat > /tmp/options.toml << EOF
          pack_directory = '$dir'
          output_file_path = '$pack.zip'
          EOF
          /tmp/packsquash /tmp/options.toml

      - name: Upload
        uses: https://code.forgejo.org/actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.pack }}
          path: ${{ steps.build.outputs.pack }}.zip