name: "CoreSync"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'modpacks/lce-core/**/mods/**'
      - 'modpacks/lce-core/**/resourcepacks/**'
      - 'modpacks/lce-core/**/resources/**'

jobs:
  sync:
    runs-on: technocality
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: blob:none

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          # Point to the new src/actions location
          workspaces: "src/actions/coresync -> target"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run CoreSync
        run: |
          cargo run --release --manifest-path src/actions/coresync/Cargo.toml

      - name: Commit and Push
        uses: https://github.com/EndBug/add-and-commit@v9
        with:
          author_name: forgejo-actions[bot]
          author_email: omo50@noreply.nostalgica.net
          message: 'actions: sync'
          add: 'modpacks'