name: Auto Refresh
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  auto-update:
    runs-on: technocality
    steps:
      - uses: actions/checkout@v5
        with: 
          token: ${{ secrets.FORGEJO_TOKEN }}
          fetch-depth: 1
          sparse-checkout: |
            modpacks

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Cache Packwiz
        id: cache-packwiz
        uses: https://github.com/actions/cache@v3
        with:
          path: ~/go/bin/packwiz
          key: packwiz-${{ runner.os }}

      - name: Install Packwiz
        if: steps.cache-packwiz.outputs.cache-hit != 'true'
        run: go install github.com/packwiz/packwiz@latest

      - name: Cache Packwiz Wrapper
        id: cache-pw-wrapper
        uses: https://github.com/actions/cache@v3
        with:
          path: ~/go/bin/pw
          key: pw-wrapper-${{ runner.os }}

      - name: Install Packwiz Wrapper
        if: steps.cache-pw-wrapper.outputs.cache-hit != 'true'
        run: go install github.com/Merith-TK/packwiz-wrapper/cmd/pw@main

      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Refresh
        run: |
          chmod +x refresh-all.sh
          ./refresh-all.sh

      - name: Commit Updates
        uses: https://github.com/EndBug/add-and-commit@v9.1.4
        with:
          author_name: forgejo-actions[bot]
          author_email: omo50@noreply.nostalgica.net
          message: 'Forgejo Actions (${{forgejo.workflow}})'
