name: Build Mash-up Pack

on:
  push:
    branches: [ "main" ]
    paths:
      - 'resourcepacks/external/lce-resources/**'
      - 'packsquash.toml'
  workflow_dispatch:

jobs:
  build:
    runs-on: technocality
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
          sparse-checkout: |
            resourcepacks
            packsquash.toml

      - name: Setup PackSquash
        run: |
          mkdir -p $HOME/.local/bin
          rm -f $HOME/.local/bin/packsquash
          
          curl -L "https://github.com/ComunidadAylas/PackSquash/releases/download/v0.4.1/packsquash-x86_64-unknown-linux-gnu.zip" -o ps.zip
          unzip -oj ps.zip -d $HOME/.local/bin/
          chmod +x $HOME/.local/bin/packsquash

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          $HOME/.local/bin/packsquash --version

      - name: Build
        id: build
        run: |
          pack=$(git diff --name-only HEAD^ HEAD \
            | grep '^resourcepacks/external/lce-resources/' \
            | sed 's|resourcepacks/external/lce-resources/\([^/]*\)/.*|\1|' \
            | sort -u | head -1)

          if [ -z "$pack" ]; then pack="halloween"; fi
          
          dir="$(pwd)/resourcepacks/external/lce-resources/$pack"
          echo "pack=$pack" >> $GITHUB_OUTPUT

          sed -i 's/\r$//' packsquash.toml
          sed -i '1s/^\xEF\xBB\xBF//' packsquash.toml

          packsquash packsquash.toml \
            --pack-directory "$dir" \
            --output-file-path "$(pwd)/$pack.zip"

          if [ -z "$pack" ]; then pack="halloween"; fi
          dir="./resourcepacks/external/lce-resources/$pack"
          echo "pack=$pack" >> $GITHUB_OUTPUT

          packsquash packsquash.toml \
            --pack-directory "$dir" \
            --output-file-path "$(pwd)/$pack.zip"

      - name: Upload
        uses: https://code.forgejo.org/actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.pack }}
          path: ${{ steps.build.outputs.pack }}.zip