name = "Simply Archaic"
author = "omo50"
version = "26.05-mc1.16.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd938a6be9dc9dfa07c79941300f3b40e260d4f9cd55bf87111d0fe24263ef29"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
