name = "Simply Archaic"
author = "omo50"
version = "26.05-mc1.16.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d9bbb0c61073e56b8c6b3438c4baa37d943cbc1c33f11928dc3e899def24030"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
