hash-format = "sha512"

[[files]]
file = "LICENSE"
hash = "..."

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "..."
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard-fabric.pw.toml"
hash = "..."
metafile = true
