name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0054"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3f8f21c75e46d627c7a1a9daea7b5c7cb0c05f7c960b5779076869b97f7c7cf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
