name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0054"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90607ec4ab66c276b238888f042c38fc2919488fa71ee8db10fa20c6b7e39180"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
