name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0054"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "366fc00fa12932145f16fc06ad8da5ae6137f6175caed6acf156e6a5b6bf190b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
