name = "Simply Optimized Forked"
author = "hsza, omo50"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e53e379230b9babe3ea6ba63fb9d572274dc31337d3eb081f86a1c2c46cd411"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
