name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03.4+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9baff145df42cbd751803e8a3e7e558a12a45fa307e5b6d60c07215a64905ae0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
