name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03.3+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8998fd34874fe5acde29053b69a5e39fbca724bc91e82ae67dd7e691cf26d88b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
