name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03.5+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26b0d0dac47e2467425930833419f582d7a933d2fb2bb3b0c3ac198144c5570f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
