name = "Legacy4Server"
author = "omo50"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e40c24b698660f7417603fccb20668b25cb31e1a857416289c7c4ca9e95986ee"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
