name = "Legacy4Server"
author = "omo50"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4abdbeecd5529ea02e09dfb94677f3db64ef8c6e892b06529def5993f35e014f"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
