name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb6ffa8fb5be3d200d3d7e959988a56febf26ee630dc337a21f042b8f7e151aa"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
