name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ac7ab030f53f64ccd4c12ffd127e8f8f0b2cbf91222d3dc6b50cac91f0676b8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
