name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "882ae0da9f8f7cebe93c50f474a476a2911e0adb2df33a200da1aa79322b8786"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
