name = "Re-Console+"
author = "omo50"
version = "26.06.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca61e2ba42daf98451976c7a775a5e93b3ea51aec06f8c4c685136a9e4fe82e1"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
