name = "Re-Console+"
author = "omo50"
version = "26.06.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beed76624887a484f810b9e355cc6b23c4709b9fdfed312eeab36adb23bb6ebc"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
