name = "Simply Archaic"
author = "omo50"
version = "26.05-mc1.8.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "187788c2be385a30dcf664489db63e8a3016e797cc15de23663b1b375a5c33ad"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
