name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2e31f13e8e794c73c7e68224a17a8c6a8ccea933c91666cadbfb9402452e798"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
