name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96de60eb186e9c293a18e873bbabf34dfa6e234f62f56b1f6ae30d23eca1a9cf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
