name = "Simply Optimized Forked"
author = "hsza, omo50"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21df3211458a5d4fd27087c73aff7929b139848f86c731280194eb426089a30b"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
