name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab0664ba84f39d234c01324f42a1c77f3e21035c31ed951bd28cdf1f55e8f046"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
