name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f625ffb45372e079dacf1ba6d052e2460f588d57cf6f3107b75a11874d46af8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
