name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "790177b8ed4db60e8b6857eddaca0e88bc75695750a934c45b26b748dcf33347"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
