name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64dd4888b80999237cb39a62bec260c7f84a64c809f246ec6c4a443cddfa61e8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
