name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b7810847e99cc0bdbf0c477cef711ca08d36f8f6ffae7f4f58a85ed94fdf27b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
