name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "545938c0feb06640b9ea75a74122d030ddfdf7c92ae9330ef4328c9c244f19e0"

[versions]
fabric = "0.19.3"
minecraft = "1.21.3"

[options]
acceptable-game-versions = []
