name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de94b3ae18adf2b9e40aca29688d63fb5e141a9cf97ddbfe187338bf5b421e84"

[versions]
fabric = "0.19.3"
minecraft = "1.21.3"

[options]
acceptable-game-versions = []
