name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d804df044e7c4694b1334b98a776029a8f4335eb1bb8d1185c3195f8395982c"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
