name = "Rekindled Legacy TU5"
author = "omo50, Panduino, Agari, hzsa, Cjnator38, AzaleaCatgirl99"
version = "26.06.0"
pack-format = "packwand:26"

[index]
file = "index.toml"
hash-format = "sha512"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
