name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb5d26dcfddaa9a4564876c4cba92692faffc20807dd45af01a261f57b32e7f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
