name = "Re-Console+"
author = "omo50, Cjnator38"
version = "26.06.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9313af4d073f5d8de81c6fa995b22a83ad240026e97afd5d29324af76ccfa739"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
