name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a0ae1e6fd582ca330f5d47005c0930f6b105465be060935e30096a0a44abc4e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
