name = "simply-modernized"
author = "omo50, hzsa"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be46dec1fc3990234e8f3b3531b5989870f3111edd2b583bd834810eadd9fea6"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
