name = "Re-Console"
author = "omo50, Cjnator38"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "261d404c809da7da392acfe8e449962fc684a09df57c705d7bdb8da0ab70fac6"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
