name = "Re-Console"
author = "omo50, Cjnator38"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92c7106b15b3a3c2c05d22ef9da98a489c4805c3f185f0c0351d7ccf31c1b559"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
