name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.04.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3f59e7f4e377e15cc3f2962bd233a9f53d3ae96ef2b6e28077c0afa6d069ba8"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
