name = "Rekindled Legacy Common"
author = "omo50, Panduino, Agari, hzsa, Cjnator38, AzaleaCatgirl99"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a14731b8bc4dc882836b421c60813d1257e92d5b8981044f7cbfc33741db529"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
