name = "Rekindled Legacy Common"
author = "omo50, Panduino, Agari, hzsa, Cjnator38, AzaleaCatgirl99"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43fb8d8ce1b72253d151e7e893080f20d3e205056f339c5b21ac6c4b32274cc4"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
