name = "Legacy4Server"
author = "omo50"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e91effa18cdb9c0a5de46e29182c052b91b9ab9dd11ed8f9f799866b351ed91"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
