name = "Legacy Console Edition Common Assets"
author = "omo50, hzsa, Cjnator38"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1aa88c0b7e60acb86acff19ae16a49f42c11f56e4f33eb3ac38f8169af475bd"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
