name = "Legacy Console Edition Common Assets"
author = "omo50, hzsa, Cjnator38"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a3bcfece47bac0f4c30e4333e779db64fe552c67b0569516fb0fcfe1f78939"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
