name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5024bcda58d6601568df43284a07f02004b56f46e64947508a6df79f2f22382"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
