name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb647e860dc6d1a4182c788fea67788f5e40a49e76616c4f3aafc970fda20863"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
