name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18bada99f4e4989f49d065b232cc1003bb4829f0f226bcbc7896bee716f10435"

[versions]
fabric = "0.19.3"
minecraft = "1.21.4"
