name = "Re-Console Plus"
author = "omo50"
version = "26.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9354934deecede31b096d583faac7c2a41d9ab52111e8e8814c44c598d1d5f09"

[versions]
fabric = "0.18.4"
minecraft = "26.1"
