name = "Re-Console Plus"
author = "omo50"
version = "26.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1607adb948c735698a2d0a690489aa988faa331347558382e0c2ab25db35f4d6"

[versions]
fabric = "0.18.4"
minecraft = "26.1"
