name = "simply-modernized"
author = "omo50, hzsa"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9242078e5cb10edb261e7f0c6c2b2b5fc82dd73f610b7ed58e5849132f823771"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
