name = "simply-modernized"
author = "omo50, hzsa"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a2d6239068679273cc0811aa088afd8ded248bcf62658230a3d14c7e25092f3"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
