name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU3"
pack-format = "packwand:26"

[index]
file = "index.toml"
hash-format = "sha512"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
