name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c26f14d146b63cd48023945b7d4a4b722fb00651779871d33b756908691bf44"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
