name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61a44e5826a7133b696217b2d89be65345d3e986da400a155f2a84101b69ed00"

[versions]
fabric = "0.19.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = []
