name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1038ec7db633237f1fd0b97904a62b0b4c2d5b6617d71d0d0b39dd33a9695e2a"

[versions]
fabric = "0.19.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = []
