name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38bed862b25965a5885383c8ad4153373bee5f2863b0388c011f3138815f53be"

[versions]
fabric = "0.19.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = []
