name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.05.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "769d79567659ec2a21b6925b455c4483da45665d76365458572c1e857c9b1e3e"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
datapack-folder = "./resources/datapack/required/"
