name = "Re-Console+"
author = "omo50"
version = "26.06.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6161c6168f4f260abcda6c83759df6857f2d3f3787a7fd2271d0c25e4db25c82"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
