name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.05.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89f54beb8e1da4d945e8cd3b9f20a0a0741547a7b52c03030364c895830e1748"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
datapack-folder = "./resources/datapack/required/"
