name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ea38a0ea5413e3f12f14ffbbb5399d2d079439919d2eb0fe7f9326446cdf7e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
