name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddf2932c31f3fd64488f01e8983a24cf2a41043ba7f2e252bd6d3fe7ae41d897"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
