name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "934dd3f9f05601392a880797684715202d0b4f3881359223ff07b41e21d1ce36"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
