use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use crate::{Error, Result, atomic_write, find};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScriptPreset {
	Build,
	Ci,
	Project,
}

impl ScriptPreset {
	pub fn parse(value: &str) -> Option<Self> {
		match value {
			"build" => Some(Self::Build),
			"ci" => Some(Self::Ci),
			"project" => Some(Self::Project),
			_ => None,
		}
	}
}

#[derive(Debug, Clone)]
pub struct ScriptRequest {
	pub name: String,
	pub preset: ScriptPreset,
	pub project: Option<String>,
	pub category: String,
	pub loader: Option<String>,
	pub force: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedScript {
	pub path: PathBuf,
	pub content: String,
	pub project: Option<String>,
}

pub fn generate_script(
	start: impl AsRef<Path>,
	request: &ScriptRequest,
) -> Result<GeneratedScript> {
	let root = repository_root(start.as_ref())?;
	let name = script_name(&request.name)?;
	let project = resolve_project(&root, start.as_ref(), request)?;
	let content = render(request, project.as_deref())?;
	let path = root.join("pw4").join(format!("{name}.pw4"));
	fs::create_dir_all(path.parent().expect("pw4 script always has a parent"))?;
	if request.force {
		atomic_write(&path, content.as_bytes())?;
	} else {
		let mut file = OpenOptions::new()
			.write(true)
			.create_new(true)
			.open(&path)
			.map_err(|error| {
				if error.kind() == std::io::ErrorKind::AlreadyExists {
					Error::ScriptAlreadyExists(path.clone())
				} else {
					Error::Io(error)
				}
			})?;
		file.write_all(content.as_bytes())?;
		file.sync_all()?;
	}
	Ok(GeneratedScript {
		path,
		content,
		project,
	})
}

fn repository_root(start: &Path) -> Result<PathBuf> {
	let canonical = fs::canonicalize(start)?;
	let directory = if canonical.is_dir() {
		canonical
	} else {
		canonical
			.parent()
			.ok_or_else(|| Error::WorkspaceRootNotFound(start.to_path_buf()))?
			.to_path_buf()
	};
	directory
		.ancestors()
		.find(|candidate| candidate.join(".git").exists())
		.map(Path::to_path_buf)
		.ok_or(Error::WorkspaceRootNotFound(directory))
}

fn script_name(value: &str) -> Result<&str> {
	let value = value.strip_suffix(".pw4").unwrap_or(value);
	if value.is_empty()
		|| value == "."
		|| value == ".."
		|| !value
			.bytes()
			.all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
	{
		return Err(Error::InvalidScriptName(value.to_owned()));
	}
	Ok(value)
}

fn validate_script_word(value: &str) -> Result<()> {
	if value.is_empty()
		|| value.starts_with('-')
		|| !value
			.bytes()
			.all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
	{
		return Err(Error::InvalidId(value.to_owned()));
	}
	Ok(())
}
fn resolve_project(root: &Path, start: &Path, request: &ScriptRequest) -> Result<Option<String>> {
	if request.preset == ScriptPreset::Project {
		return Ok(request.project.clone());
	}
	if let Some(id) = &request.project {
		find(root, id)?;
		return Ok(Some(id.clone()));
	}
	let canonical = fs::canonicalize(start)?;
	for category in ["mods", "modpacks", "datapacks", "resourcepacks"] {
		let category_root = root.join(category);
		if let Ok(relative) = canonical.strip_prefix(&category_root)
			&& let Some(id) = relative.components().next()
		{
			let id = id.as_os_str().to_string_lossy().into_owned();
			find(root, &id)?;
			return Ok(Some(id));
		}
	}
	Ok(None)
}

fn render(request: &ScriptRequest, project: Option<&str>) -> Result<String> {
	if let Some(project) = project {
		validate_script_word(project)?;
	}
	let mut output =
		String::from("// Generated by packwand script. Safe to run locally or in CI.\n");
	match request.preset {
		ScriptPreset::Build | ScriptPreset::Ci => {
			if request.preset == ScriptPreset::Ci {
				output.push_str("// CI entry point: builds the selected or changed projects.\n");
			}
			output.push_str("build");
			if let Some(project) = project {
				output.push(' ');
				output.push_str(project);
			}
			output.push('\n');
		}
		ScriptPreset::Project => {
			let project =
				project.ok_or_else(|| Error::MissingScriptProject("project preset".to_owned()))?;
			let flag = match request.category.as_str() {
				"modpack" | "modpacks" => "-mp",
				"datapack" | "datapacks" => "-dp",
				"resourcepack" | "resourcepacks" => "-rp",
				"mod" | "mods" => "-md",
				value => return Err(Error::InvalidCategory(value.to_owned())),
			};
			output.push_str("project setup ");
			output.push_str(project);
			output.push(' ');
			output.push_str(flag);
			if let Some(loader) = &request.loader {
				super::validate_loader(loader)?;
				output.push_str(" --");
				output.push_str(loader);
			}
			output.push('\n');
		}
	}
	Ok(output)
}

#[cfg(test)]
mod tests {
	use super::*;

	fn repository() -> tempfile::TempDir {
		let root = tempfile::tempdir().unwrap();
		fs::create_dir(root.path().join(".git")).unwrap();
		root
	}

	#[test]
	fn creates_pw4_at_repository_root_from_nested_directory() {
		let root = repository();
		let nested = root.path().join("tools/nested");
		fs::create_dir_all(&nested).unwrap();
		let generated = generate_script(
			&nested,
			&ScriptRequest {
				name: "ci".to_owned(),
				preset: ScriptPreset::Ci,
				project: None,
				category: "modpack".to_owned(),
				loader: None,
				force: false,
			},
		)
		.unwrap();
		assert_eq!(
			generated.path,
			fs::canonicalize(root.path()).unwrap().join("pw4/ci.pw4")
		);
		assert!(generated.content.ends_with("build\n"));
	}

	#[test]
	fn build_preset_infers_project_from_nested_working_directory() {
		let root = repository();
		crate::create_project(
			root.path(),
			&crate::NewProject {
				category: "datapacks".to_owned(),
				id: "context-pack".to_owned(),
				name: None,
				minecraft_version: None,
				loader: None,
				variants: Vec::new(),
				role: crate::ProjectRole::None,
			},
		)
		.unwrap();
		let nested = root.path().join("datapacks/context-pack/data/example");
		fs::create_dir_all(&nested).unwrap();
		let generated = generate_script(
			&nested,
			&ScriptRequest {
				name: "context".to_owned(),
				preset: ScriptPreset::Build,
				project: None,
				category: "modpack".to_owned(),
				loader: None,
				force: false,
			},
		)
		.unwrap();
		assert_eq!(generated.project.as_deref(), Some("context-pack"));
		assert!(generated.content.ends_with("build context-pack\n"));
	}
	#[test]
	fn project_preset_renders_kind_and_loader() {
		let root = repository();
		let generated = generate_script(
			root.path(),
			&ScriptRequest {
				name: "new-content.pw4".to_owned(),
				preset: ScriptPreset::Project,
				project: Some("new-content".to_owned()),
				category: "datapack".to_owned(),
				loader: Some("fabric".to_owned()),
				force: false,
			},
		)
		.unwrap();
		assert!(
			generated
				.content
				.contains("project setup new-content -dp --fabric")
		);
	}

	#[test]
	fn refuses_traversal_and_existing_scripts() {
		let root = repository();
		let mut request = ScriptRequest {
			name: "../outside".to_owned(),
			preset: ScriptPreset::Build,
			project: None,
			category: "modpack".to_owned(),
			loader: None,
			force: false,
		};
		assert!(matches!(
			generate_script(root.path(), &request),
			Err(Error::InvalidScriptName(_))
		));
		request.name = "safe".to_owned();
		request.preset = ScriptPreset::Project;
		request.project = Some("bad\nproject".to_owned());
		assert!(matches!(
			generate_script(root.path(), &request),
			Err(Error::InvalidId(_))
		));
		request.name = "build".to_owned();
		request.preset = ScriptPreset::Build;
		request.project = None;
		generate_script(root.path(), &request).unwrap();
		assert!(matches!(
			generate_script(root.path(), &request),
			Err(Error::ScriptAlreadyExists(_))
		));
	}
}
