name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae103bce81e736f4e5d37de8a44d85e327e2b0ff882c1e90ccb39c027cbe7b3e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
