name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "342e786c0f4bd3730a5e74d14f9956bce5c03b166c93e3013308c8f224c8567d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
