name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.03.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61199ab91bc474703476a150ca4bf39a87f204bf06281af1bea59403e42c9d19"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
