name = "Re-Console+"
author = "omo50"
version = "26.06.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4e17e553db63c8fb4b65babf761c5333be88a0b90427ea778b730e3b6dc7ab8"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
