name = "Gold Not Old"
author = "Cjnator38"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d71af79bc184e74dc575640b12d101c73dfaf3398b6823e7c2441299f7bae7e7"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
