name = "Gold Not Old"
author = "Cjnator38"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "101e170c5e01bb094c6f3b2f4b84a5ca87b9028d97c70ea761b4f0494ecc0d38"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
