name = "MinigameClient"
author = "omo50"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01ac69892ec206f20769c14da2aab7afa9fccc319536aa07ce40db73fbae538c"

[versions]
fabric = "0.19.3"
minecraft = "1.20.4"
