name = "MinigameClient"
author = "omo50"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "594f986c2c2a240150f11dc221043473ec615eea3e61ca87d0a1aa971d22bea7"

[versions]
fabric = "0.19.2"
minecraft = "1.20.4"
