name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f79f9618089f355fb4f546673ca874f7f0d9696c8202241b7b6f5926b1801619"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
datapack-folder = "./resources/datapack/required/"
