name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6824d7c5f8cd349aa668152b0868d47b9bc2c0aa604f03b5a978ccc1ad27450f"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
datapack-folder = "./resources/datapack/required/"
