name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.05.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "810e620a913f293dbbd53b73292de07f3d399533868e01b1d5aaf4bac564c585"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
datapack-folder = "./resources/datapack/required/"
