name = "Re-Console LTS"
author = "omo50, Cjnator38"
version = "26.04.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba193f65c441374f2f0b34b9319dabdb7f9db5e704de96362bea1249d655a7cd"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
datapack-folder = "./resources/datapack/required/"
