name = "Re-Console LTS"
author = "omo50, Cjnator38"
version = "26.04.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "063fe6354d08bd17e35c74f5aad27da2c8c4bffe36d526b223e8b53cc363a3e7"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
datapack-folder = "./resources/datapack/required/"
