name = "Simply Archaic"
author = "omo50"
version = "26.05-mc1.7.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "388f3f7f45bd7975add3741d799f5ebc934dd72e4ce14fb8ab3444c70fe8e8b4"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
