name = "Simply Archaic"
author = "omo50"
version = "26.05-mc1.7.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "638a0c3f13c6afea3d74bc0f5698cae6d767afc41432a522b289661e50f0c063"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
