name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0033"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b91aa9cb715f8c0042fed162c9f73a425286b7e8a66bc916d66d0af29be3054d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
