name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0033"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a19980cefca1cd08c3bd8837e74dcd7b2383c5eb2341cadd8ed5fa3c97bf419e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
