name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0033"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c6604826205e93aed67c9194cf098b9ce42a97740c72f6f78ddec5e4d599ffb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
