name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b8b88e306fad8d58d1e87691414f8aecac0a854b4ec23345f89c3741efad4b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
