name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5534760745be7bc01057ae85f687bb1070131e7cbb297a7cbfa5ce4a9eb2e36c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
