name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edfd8821b311b943446e09a7bf9a8d65401ee5c706df28c1ab8a41cfa09891c4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
