name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.04.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44409a3d9f74de5efc8b94fd1ed9366effbdb137cc585bf9c266e5ec4703131c"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
