name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.04.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be8b693fe2847820cd168f0c37cb62d8162c53aed5f98259d6f2f7d2ffd0eef0"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
