name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.04.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e86e8c0c8fa392b40e018f7cf822e59ea6bb9b2292df1ecd7aa6d6b83ed655b4"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
