name = "Gold Not Old"
author = "Cjnator38"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0b162842c770bfed66cfdd1be58ccc847962b701d4be339194ae8742277a548"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
