name = "Gold Not Old"
author = "Cjnator38"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ba22c8fbc16eb9c0a97cf59e03c2f29fc9df72ef32e348dc878807f5267b6c2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
