name = "Gold Not Old"
author = "Cjnator38"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d954d4d5a5bb08676ea805a3005b0e4da1ffe925d457ce73f4b4cde4daa2e16c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
