name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f536d0e898ec8659cb112a9ec07c7b94c317be6bce33a01aceecf3a6252788c2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
