name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ebf4ae8bc1e94b291bcb61c0f57c3844469f54bd8d6a6a4043d93d68230fd2c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
