name = "Simply Archaic"
author = "omo50"
version = "26.05-mc1.18.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd0ed6d22d89a9a5b6a645512cc845b43af400c68e9e4b8ebe2443bf551ad388"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
