name = "Simply Archaic"
author = "omo50"
version = "26.05-mc1.16.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbd2f36c7c3c2481a464cf5ccc71b4fd28af3274fcf2b3aae948612fd30de2ae"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
