name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0035"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39f279208ec26b53ecf130377bc94b5fb762cceadbef64bd061761b94848f1a6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
