name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0035"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dce2c161e32e3876e6574118eadc00a0f2d5effdc4701703d1fe1ded6127d8a2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
