name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0035"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40e976543a1bc63b15fb8bd9d573281b855b248943ed61b253d7ed148abb2342"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
