name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwand:26"

[index]
file = "index.toml"
hash-format = "sha512"
hash = "f125f1cdbf4237e978a12fc40bbf0c954ea2749c83cfe25d4e6eb35e9cead7cc82121b1384db6fd85cdbbf071f1acbedf8d6bf46742112335ecba12a20b2e718"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
