name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba1c26086c08224c85026cefb16fba94e81b2441603f42bf1ab5f487a8069767"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
