name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92716aefb375557f28d73c183fe62b0a69f38043ed208e51e759d70d1911aa9f"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
