gamerule.legacy:legacy_mobcap_limits=true
gamerule.legacy:legacy_offhand_limits=true
gamerule.legacy:legacy_shield_controls=true
gamerule.minecraft:locator_bar=false
gamerule.minecraft:show_advancement_messages=false
