name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0035"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e45a019a3f92fda4052f4954cca1be2c51205403f464e2537e37c9d5ba2e43da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
