name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0035"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ff5ddacc9d7ff458f337641c8ebdebdb565c40e9b70bb35337da0dd92413937"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
