name = "Reimagined Legacy"
author = "omo50, Cjnator38"
version = "26.05-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8925369739e4bdf24e348c2bb9d650a411ea7db1bd662f9379261cfb172091dd"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
