name = "Reimagined Legacy"
author = "omo50, Cjnator38"
version = "26.05-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "290bd4c819909f3ae218be82639e862346c8d8b7262ed496c77b3359e5166c23"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
