name = "Reimagined Legacy"
author = "omo50, Cjnator38"
version = "26.05-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42cfd6c477f96468ee4b96151792a2a89fe5cf7f20ca6e1f098f3fa97e6d2cf4"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
