name = "qualt"
author = "omo50, intergrav, blryface"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "726f5c9e25a157600b5db4d8f90ceccd923cf9868418aec543dc28a0879f59fb"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
