name = "qualt"
author = "omo50"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43971a8767a22cd2c823d4b989e1a9c6a2762824a664a451fe5c382eaa37d7e2"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
