name = "qualt"
author = "omo50"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beffc89651f8cb6b7286dbd029f0d4dbcfcb6e5316215736946c4ec8e78ca86e"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
