name = "lce-core"
author = "omo50"
version = "26.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "459ada348edcf8ab77907e1cd4bbb641028d8088a5f6760846c1fe47c114e214"

[versions]
fabric = "0.19.1"
minecraft = "1.21.10"
