name = "lce-core"
author = "omo50"
version = "26.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95a8452c8c315a32a6aaeceb30075701c807d26c3885f6c0cea78012cd836b29"

[versions]
fabric = "0.19.1"
minecraft = "1.21.10"
