name = "Simply Archaic"
author = "omo50"
version = "26.05-mc1.12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "097a54ebabbd65902d68f94fa00238ad886b59148a86bd9d3c08a06efe435ff4"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
