name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.04.1+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac7bee0b635d86491febe26651ee232b5715d9738e4aba1959aa52a375a2c018"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
