name = "Re-Console+"
author = "omo50, Technocality, Cjnator38"
version = "26.04.1+mc1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2faebbd3e1d2ce1706b8af50620d6894e3ecb62b6ed05539586a883681c1932d"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
