#Modernica mixin configuration. Restart Minecraft after editing.
#Mon Aug 03 17:19:28 CDT 2026
mixin.bugfix.chunk_deadlock=true
mixin.bugfix.cofh_core_crash=true
mixin.bugfix.concurrency=true
mixin.bugfix.end_island_overflow=true
mixin.bugfix.extra_experimental_screen=true
mixin.bugfix.missing_block_entities=false
mixin.bugfix.paper_chunk_patches=true
mixin.bugfix.recipe_book_type_desync=true
mixin.bugfix.restore_old_dragon_movement=false
mixin.bugfix.singleplayer_keepalive_kick=true
mixin.bugfix.unsafe_modded_shape_caches=true
mixin.bugfix.world_leaks=true
mixin.bugfix.world_screen_skipped=true
mixin.core=true
mixin.devenv=false
mixin.feature.blockentity_incorrect_thread=false
mixin.feature.branding=true
mixin.feature.cause_lag_by_disabling_threads=false
mixin.feature.direct_stack_trace=false
mixin.feature.fast_ip_ping=true
mixin.feature.force_close_loading_screen=false
mixin.feature.integrated_server_watchdog=true
mixin.feature.mcfunction_profiling=true
mixin.feature.measure_time=true
mixin.feature.remove_chat_signing=false
mixin.feature.remove_telemetry=true
mixin.feature.snapshot_easter_egg=true
mixin.feature.spam_thread_dump=false
mixin.feature.spark_profile_launch=false
mixin.feature.spark_profile_world_join=true
mixin.feature.stalled_chunk_load_detection=false
mixin.feature.suppress_narrator_stacktrace=true
mixin.perf.attribute_supplier_dedup=true
mixin.perf.bad_optimizations.debug_renderer_culling=true
mixin.perf.bad_optimizations.particle_culling=true
mixin.perf.bad_optimizations.skip_non_demo_tutorial=true
mixin.perf.bad_optimizations.toast_culling=true
mixin.perf.bad_optimizations.zero_fov_calculation=true
mixin.perf.block_counting=true
mixin.perf.blockstate_propertyaccess=true
mixin.perf.cache_blockstate_cache_arrays=true
mixin.perf.cache_profile_texture_url=true
mixin.perf.cache_strongholds=true
mixin.perf.chunk_meshing=true
mixin.perf.clear_mixin_classinfo=false
mixin.perf.compact_bit_storage=true
mixin.perf.compact_entity_models=true
mixin.perf.compact_imposterprotochunks=true
mixin.perf.compact_mojang_registries=true
mixin.perf.compress_unihex_font=true
mixin.perf.datapack_reload_exceptions=true
mixin.perf.dedicated_reload_executor=true
mixin.perf.deduplicate_advancement_predicates=true
mixin.perf.deduplicate_climate_parameters=true
mixin.perf.deduplicate_location=true
mixin.perf.deduplicate_nbt_strings=true
mixin.perf.deduplicate_wall_shapes=true
mixin.perf.dynamic_dfu=true
mixin.perf.dynamic_entity_renderers=false
mixin.perf.dynamic_languages=true
mixin.perf.dynamic_resources=true
mixin.perf.dynamic_sounds=true
mixin.perf.dynamic_structure_manager=true
mixin.perf.encoder_cache_leak=true
mixin.perf.fast_bitstorage=true
mixin.perf.fast_block_entity_removal=true
mixin.perf.fast_palette=true
mixin.perf.faster_command_suggestions=true
mixin.perf.faster_item_rendering=true
mixin.perf.faster_texture_stitching=true
mixin.perf.game_thread_priority=true
mixin.perf.getblock=true
mixin.perf.lazy_search_tree_registry=true
mixin.perf.memoize_creative_tab_build=true
mixin.perf.mob_spawning=true
mixin.perf.model_optimizations=true
mixin.perf.mojang_registry_size=true
mixin.perf.network_enhancements=true
mixin.perf.network_optimizations=true
mixin.perf.poi_lookup=true
mixin.perf.random_ticking=true
mixin.perf.release_protochunks=true
mixin.perf.remove_biome_temperature_cache=true
mixin.perf.resourcepacks=true
mixin.perf.state_definition_construct=true
mixin.perf.tag_id_caching=true
mixin.perf.thread_priorities=true
mixin.perf.thread_unsafe_random=true
mixin.perf.ticking_chunk_alloc=true
mixin.perf.worldgen_allocation=true
