name = "qualt"
author = "omo50"
version = "26.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72a7379732eba0ba012dc2a549b4374c520535cca93fe93cdfc548330e6f6c09"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
