name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.04.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f2697383e186c64b6a5d23074a278150131895d1d91e1dbac32c340bcea7659"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
