name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.04.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be5a3a6390760f61a7b6331749f7a7520c2ba6e17a0f48a0d19fc1e7d4559e8f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
