name = "Re-Console Plus"
author = "omo50, Cjnator38"
version = "26.04.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e19cf42bd04a39669577f3a7766731e87a607491df050905c51b7e1882dcf72"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"

[options]
datapack-folder = "./resources/datapack/required/"
