name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0054"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29a061f498bc04ffa3f702e870b04b5d54ef5388b44bba9db42e1bcce332c1e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
