name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-build-0054"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39cff1750b4a97489896f8e9a50224770ed3cafe678683f740d8a6d2a7c36a94"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
