name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd23a720de16703bd3971bf64323d5578bfa9846133c543c552a5d504eae7e6c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
