name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "450981f602a5ed45ba8d7ce369275e3067e61ee997d541946b82f57ba357889b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
