name = "Rekindled Legacy"
author = "omo50, Agari, Panduino"
version = "25.0.3-TU2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88e085f058b8e994c725466b282d1d85d0df889d9cdd68ddba649f47a0abd3c0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = []
