name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a6262947d77be1feabb1fb7c75b14d7542ffea0220bbd7f848216683d3b3b70"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
