name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b13c9ff62513b9b6ef50d21143880539b926b8de1b654ceafadb1d50b882673d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
