name = "Re-Console"
author = "omo50, Technocality, Cjnator38"
version = "26.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "010f016a116ccfac2f85f2797fa49d7f4f98e569b0fb67cc569bdb925399469c"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
